#!/usr/bin/env python3
'''
Script de migración automática para VIGOLEONROCKS
Generado por VIGOLEONROCKS Architect Reorganizer
'''

import shutil
import os
from pathlib import Path

def reorganize_vigoleonrocks(dry_run=True):
    project_root = Path(__file__).parent
    backup_dir = project_root / '_backup_original_structure'
    new_structure_dir = project_root / '_new_optimized_structure'
    
    print('🚀 Iniciando reorganización de VIGOLEONROCKS...')
    
    if not dry_run:
        # Crear backup
        if backup_dir.exists():
            shutil.rmtree(backup_dir)
        print('📦 Creando backup...')
        shutil.copytree(project_root, backup_dir, ignore=shutil.ignore_patterns('_backup_*', '_new_optimized_*'))
        
        # Crear estructura objetivo  
        if new_structure_dir.exists():
            shutil.rmtree(new_structure_dir)
        new_structure_dir.mkdir()
    
    # Ejecutar movimientos
    movements = {
        ".": "vigoleonrocks-core",
        "localGPT-main": "application",
        "mcp\\core": "vigoleonrocks-core",
        "services\\quantum-core": "vigoleonrocks-core",
        "cache": "infrastructure",
        "dokploy-canary\\apps\\api": "interfaces",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\build": "interfaces",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\preview-deployments": "interfaces",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\api": "interfaces",
        "dokploy-canary\\apps\\dokploy\\components\\ui": "interfaces",
        "dokploy-canary\\apps\\dokploy\\pages\\api": "interfaces",
        "dokploy-canary\\apps\\dokploy\\server\\api": "interfaces",
        "dokploy-canary\\apps\\dokploy\\server\\api\\routers": "interfaces",
        "dokploy-canary\\apps\\dokploy\\templates": "interfaces",
        "dokploy-canary\\apps\\dokploy\\__test__\\templates": "interfaces",
        "dokploy-canary\\apps\\monitoring\\database": "infrastructure",
        "dokploy-canary\\packages\\server\\src\\templates": "interfaces",
        "dokploy-canary\\packages\\server\\src\\utils\\builders": "interfaces",
        "dokploy-canary\\packages\\server\\src\\utils\\databases": "infrastructure",
        "openvpn-gui-master": "interfaces",
        "services\\api-gateway": "interfaces",
        "services\\cache": "infrastructure",
        "services\\database": "infrastructure",
        "config": "config",
        "dokploy-canary": "application",
        "dokploy-canary\\.vscode": "application",
        "dokploy-canary\\apps\\api\\src": "application",
        "dokploy-canary\\apps\\dokploy": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\cluster": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\import": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\ports": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\redirects": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\security": "security",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\traefik": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\advanced\\volumes": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\deployments": "deployment",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\domains": "domain",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\environment": "config",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\general\\generic": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\logs": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\rollbacks": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\schedules": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\application\\volume-backups": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\compose": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\compose\\advanced": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\compose\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\compose\\general\\generic": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\compose\\logs": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\database\\backups": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\docker\\config": "config",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\docker\\logs": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\docker\\show": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\docker\\terminal": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\file-system": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\impersonation": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mariadb": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mariadb\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mongo": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mongo\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\monitoring\\free\\container": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\monitoring\\paid\\container": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\monitoring\\paid\\servers": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mysql": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\mysql\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\organization": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\postgres": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\postgres\\advanced": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\postgres\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\project": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\project\\ai": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\projects": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\redis": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\redis\\general": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\requests": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings": "config",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\billing": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\certificates": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\cluster\\nodes": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\cluster\\nodes\\manager": "domain",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\cluster\\nodes\\workers": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\cluster\\registry": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\destination": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\git": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\git\\bitbucket": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\git\\gitea": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\git\\github": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\git\\gitlab": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\notifications": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\profile": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\servers": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\servers\\actions": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\servers\\welcome-stripe": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\ssh-keys": "security",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\users": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\settings\\web-server": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\shared": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\swarm": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\swarm\\applications": "application",
        "dokploy-canary\\apps\\dokploy\\components\\dashboard\\swarm\\details": "application",
        "dokploy-canary\\apps\\dokploy\\components\\icons": "application",
        "dokploy-canary\\apps\\dokploy\\components\\layouts": "application",
        "dokploy-canary\\apps\\dokploy\\components\\shared": "application",
        "dokploy-canary\\apps\\dokploy\\drizzle": "application",
        "dokploy-canary\\apps\\dokploy\\drizzle\\meta": "application",
        "dokploy-canary\\apps\\dokploy\\hooks": "application",
        "dokploy-canary\\apps\\dokploy\\lib": "application",
        "dokploy-canary\\apps\\dokploy\\pages": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\accept-invitation": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\auth": "security",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\deploy": "deployment",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\deploy\\compose": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\providers\\gitea": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\providers\\github": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\providers\\gitlab": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\stripe": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\api\\trpc": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\application": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\compose": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\mariadb": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\mongo": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\mysql": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\postgres": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\project\\[projectId]\\services\\redis": "application",
        "dokploy-canary\\apps\\dokploy\\pages\\dashboard\\settings": "config",
        "dokploy-canary\\apps\\dokploy\\public": "application",
        "dokploy-canary\\apps\\dokploy\\public\\avatars": "application",
        "dokploy-canary\\apps\\dokploy\\public\\images": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\az": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\de": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\en": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\es": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\fa": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\fr": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\id": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\it": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\ja": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\ko": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\kz": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\ml": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\nl": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\no": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\pl": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\pt-br": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\ru": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\tr": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\uk": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\zh-Hans": "application",
        "dokploy-canary\\apps\\dokploy\\public\\locales\\zh-Hant": "application",
        "dokploy-canary\\apps\\dokploy\\server": "application",
        "dokploy-canary\\apps\\dokploy\\server\\db": "application",
        "dokploy-canary\\apps\\dokploy\\server\\db\\schema": "application",
        "dokploy-canary\\apps\\dokploy\\server\\db\\validations": "application",
        "dokploy-canary\\apps\\dokploy\\server\\queues": "application",
        "dokploy-canary\\apps\\dokploy\\server\\utils": "tools",
        "dokploy-canary\\apps\\dokploy\\server\\wss": "application",
        "dokploy-canary\\apps\\dokploy\\styles": "application",
        "dokploy-canary\\apps\\dokploy\\templates\\utils": "tools",
        "dokploy-canary\\apps\\dokploy\\types": "application",
        "dokploy-canary\\apps\\dokploy\\utils": "tools",
        "dokploy-canary\\apps\\dokploy\\utils\\hooks": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\config": "config",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\domain": "domain",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\network": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\secrets": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\service": "domain",
        "dokploy-canary\\apps\\dokploy\\__test__\\compose\\volume": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\deploy": "deployment",
        "dokploy-canary\\apps\\dokploy\\__test__\\drop": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\drop\\zips": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\drop\\zips\\folder1": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\drop\\zips\\folder2": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\drop\\zips\\folder3": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\env": "config",
        "dokploy-canary\\apps\\dokploy\\__test__\\requests": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\traefik": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\traefik\\server": "application",
        "dokploy-canary\\apps\\dokploy\\__test__\\utils": "tools",
        "dokploy-canary\\apps\\monitoring": "application",
        "dokploy-canary\\apps\\monitoring\\config": "config",
        "dokploy-canary\\apps\\monitoring\\containers": "application",
        "dokploy-canary\\apps\\monitoring\\middleware": "application",
        "dokploy-canary\\apps\\monitoring\\monitoring": "application",
        "dokploy-canary\\apps\\schedules": "application",
        "dokploy-canary\\apps\\schedules\\src": "application",
        "dokploy-canary\\packages\\server": "application",
        "dokploy-canary\\packages\\server\\scripts": "tools",
        "dokploy-canary\\packages\\server\\src": "application",
        "dokploy-canary\\packages\\server\\src\\auth": "security",
        "dokploy-canary\\packages\\server\\src\\constants": "application",
        "dokploy-canary\\packages\\server\\src\\db": "application",
        "dokploy-canary\\packages\\server\\src\\db\\schema": "application",
        "dokploy-canary\\packages\\server\\src\\db\\validations": "application",
        "dokploy-canary\\packages\\server\\src\\emails": "application",
        "dokploy-canary\\packages\\server\\src\\emails\\emails": "application",
        "dokploy-canary\\packages\\server\\src\\emails\\emails\\static": "application",
        "dokploy-canary\\packages\\server\\src\\lib": "application",
        "dokploy-canary\\packages\\server\\src\\monitoring": "application",
        "dokploy-canary\\packages\\server\\src\\services": "domain",
        "dokploy-canary\\packages\\server\\src\\setup": "application",
        "dokploy-canary\\packages\\server\\src\\types": "application",
        "dokploy-canary\\packages\\server\\src\\utils": "tools",
        "dokploy-canary\\packages\\server\\src\\utils\\access-log": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\ai": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\backups": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\cluster": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\docker\\collision": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\docker\\compose": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\filesystem": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\notifications": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\process": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\providers": "integrations",
        "dokploy-canary\\packages\\server\\src\\utils\\restore": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\schedules": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\servers": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\traefik": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\volume-backups": "application",
        "dokploy-canary\\packages\\server\\src\\utils\\watch-paths": "application",
        "dokploy-canary\\packages\\server\\src\\verification": "application",
        "dokploy-canary\\packages\\server\\src\\wss": "application",
        "localGPT-main\\WebAgent_Santuario": "application",
        "localGPT-main\\WebAgent_Santuario\\unified_chroma_db": "application",
        "mcp": "application",
        "mcp\\config": "config",
        "mcp\\exports": "application",
        "mcp\\services": "domain",
        "openvpn-gui-master\\plap": "application",
        "openvpn-gui-master\\qrcodegen": "application",
        "openvpn-gui-master\\res": "application",
        "services\\message-broker": "application",
        "services\\product-a": "application",
        "services\\product-b": "application",
        "src": "application",
        "dokploy-canary\\apps\\dokploy\\docker": "docs",
        "dokploy-canary\\apps\\dokploy\\__test__": "tests",
        "dokploy-canary\\packages\\server\\src\\utils\\docker": "docs"
}
    
    for src_path, dst_path in movements.items():
        src = project_root / src_path
        dst = new_structure_dir / dst_path
        
        if dry_run:
            print(f'[DRY RUN] {src} -> {dst}')
        else:
            if src.exists():
                dst.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(src), str(dst))
                print(f'Movido: {src.name}')
    
    print('✅ Reorganización completada!')

if __name__ == '__main__':
    import sys
    dry_run = '--dry-run' in sys.argv
    reorganize_vigoleonrocks(dry_run)
