# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_pnl_position_updates.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"request_pnl_position_updates.proto\x12\x03rti\"\xfe\x01\n\x19RequestPnLPositionUpdates\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x39\n\x07request\x18\xa0\x8d\x06 \x01(\x0e\x32&.rti.RequestPnLPositionUpdates.Request\x12\x10\n\x06\x66\x63m_id\x18\x9d\xb3\t \x01(\t\x12\x0f\n\x05ib_id\x18\x9e\xb3\t \x01(\t\x12\x14\n\naccount_id\x18\x98\xb3\t \x01(\t\"B\n\x07Request\x12\x17\n\x13REQUEST_UNSPECIFIED\x10\x00\x12\r\n\tSUBSCRIBE\x10\x01\x12\x0f\n\x0bUNSUBSCRIBE\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'request_pnl_position_updates_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTPNLPOSITIONUPDATES']._serialized_start=44
  _globals['_REQUESTPNLPOSITIONUPDATES']._serialized_end=298
  _globals['_REQUESTPNLPOSITIONUPDATES_REQUEST']._serialized_start=232
  _globals['_REQUESTPNLPOSITIONUPDATES_REQUEST']._serialized_end=298
# @@protoc_insertion_point(module_scope)
