# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_tick_bar_replay.proto
# Protobuf Python Version: 4.25.4
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eresponse_tick_bar_replay.proto\x12\x03rti\"\xd0\x05\n\x15ResponseTickBarReplay\x12\x15\n\x0btemplate_id\x18\xe3\xb6\t \x01(\x05\x12\x15\n\x0brequest_key\x18\x96\x8d\x08 \x01(\t\x12\x12\n\x08user_msg\x18\x98\x8d\x08 \x03(\t\x12\x1c\n\x12rq_handler_rp_code\x18\x9c\x8d\x08 \x03(\t\x12\x11\n\x07rp_code\x18\x9e\x8d\x08 \x03(\t\x12\x10\n\x06symbol\x18\x94\xdc\x06 \x01(\t\x12\x12\n\x08\x65xchange\x18\x95\xdc\x06 \x01(\t\x12\x32\n\x04type\x18\xa0\xa3\x07 \x01(\x0e\x32\".rti.ResponseTickBarReplay.BarType\x12\x39\n\x08sub_type\x18\xa8\xa3\x07 \x01(\x0e\x32%.rti.ResponseTickBarReplay.BarSubType\x12\x18\n\x0etype_specifier\x18\xc2\x85\t \x01(\t\x12\x14\n\nnum_trades\x18\xa4\xa3\x07 \x01(\x04\x12\x10\n\x06volume\x18\xa5\xa3\x07 \x01(\x04\x12\x14\n\nbid_volume\x18\xad\xa3\x07 \x01(\x04\x12\x14\n\nask_volume\x18\xae\xa3\x07 \x01(\x04\x12\x14\n\nopen_price\x18\xb3\x8d\x06 \x01(\x01\x12\x15\n\x0b\x63lose_price\x18\xb5\x8d\x06 \x01(\x01\x12\x14\n\nhigh_price\x18\xac\x8d\x06 \x01(\x01\x12\x13\n\tlow_price\x18\xad\x8d\x06 \x01(\x01\x12!\n\x17\x63ustom_session_open_ssm\x18\xa9\xa3\x07 \x01(\x05\x12\x18\n\x0e\x64\x61ta_bar_ssboe\x18\xa2\xa3\x07 \x03(\x05\x12\x18\n\x0e\x64\x61ta_bar_usecs\x18\xa3\xa3\x07 \x03(\x05\"O\n\x07\x42\x61rType\x12\x17\n\x13\x42\x41RTYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08TICK_BAR\x10\x01\x12\r\n\tRANGE_BAR\x10\x02\x12\x0e\n\nVOLUME_BAR\x10\x03\"A\n\nBarSubType\x12\x1a\n\x16\x42\x41RSUBTYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07REGULAR\x10\x01\x12\n\n\x06\x43USTOM\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'response_tick_bar_replay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESPONSETICKBARREPLAY']._serialized_start=40
  _globals['_RESPONSETICKBARREPLAY']._serialized_end=760
  _globals['_RESPONSETICKBARREPLAY_BARTYPE']._serialized_start=614
  _globals['_RESPONSETICKBARREPLAY_BARTYPE']._serialized_end=693
  _globals['_RESPONSETICKBARREPLAY_BARSUBTYPE']._serialized_start=695
  _globals['_RESPONSETICKBARREPLAY_BARSUBTYPE']._serialized_end=760
# @@protoc_insertion_point(module_scope)
