# ==============================================================================
# || QBTC UNIFIED SYSTEM - APISIX DECLARATIVE CONFIGURATION                 ||
# ==============================================================================
#
# Este archivo define las rutas, servicios (upstreams), y plugins de APISIX
# de forma declarativa. APISIX lo leerá al iniciar en modo 'standalone'.
#

# ------------------------------------------------------------------------------
# -- GLOBAL PLUGINS (Se aplican a todas las rutas)
# ------------------------------------------------------------------------------
# global_rules:
#   - id: 1
#     plugins:
#       limit-req:
#         rate: 100
#         burst: 50
#         rejected_code: 503

# ------------------------------------------------------------------------------
# -- UPSTREAMS (Servicios a los que APISIX enrutará el tráfico)
# ------------------------------------------------------------------------------
upstreams:
  # Placeholder para el servicio que expondrá la API del LLM
  - id: llm_api_service_upstream
    name: "LLM API Service"
    type: roundrobin
    # Los nodos se añadirán cuando el servicio esté implementado
    nodes:
      "llm-api-service:8000": 1 # Corregido al puerto 8000, donde Uvicorn corre.
    # health check para el servicio
    checks:
      active:
        type: http
        http_path: "/health"
        healthy:
          successes: 2
          http_statuses: [200]
        unhealthy:
          http_statuses: [500, 503]
          http_failures: 3
          tcp_failures: 3
          timeouts: 3
        req_headers: ["User-Agent: APISIX-Health-Check"]
      passive:
        healthy:
          http_statuses: [200, 201]
          successes: 3
        unhealthy:
          http_statuses: [500, 503]
          http_failures: 3
          tcp_failures: 3
          timeouts: 3

# ------------------------------------------------------------------------------
# -- RUTAS (Paths que el cliente puede solicitar)
# ------------------------------------------------------------------------------
routes:
  # Ruta de Health Check para el propio APISIX
  - id: health_check_route
    name: "APISIX Health Check"
    uri: /health
    methods: [GET, HEAD]
    plugins:
      # Plugin que responde directamente sin ir a un upstream
      mocking:
        response_body: '{"status":"ok", "gateway":"APISIX"}'
        response_headers:
          Content-Type: "application/json"

  # Ruta principal para el producto LLM Cuántico
  - id: llm_api_v1_route
    name: "LLM API v1"
    uri: /v1/chat/completions
    methods: [POST, OPTIONS]
    # Asocia esta ruta con el upstream del servicio LLM
    upstream_id: llm_api_service_upstream
    plugins:
      # Habilitar CORS para que clientes como ROO CODE puedan acceder
      cors: {}
      # Proteger la ruta con una clave de API
      key-auth: {}
      # Plugin de reescritura, puede ser útil más adelante
      # proxy-rewrite:
      #   regex_uri: ["/v1/(.*)", "/$1"]
    
  # Ruta para métricas de Prometheus
  - id: apisix_metrics_route
    name: "APISIX Prometheus Metrics"
    uri: /apisix/prometheus/metrics
    methods: [GET]
    plugins:
      prometheus: {}

# ------------------------------------------------------------------------------
# -- CONSUMERS (Clientes de la API)
# ------------------------------------------------------------------------------
consumers:
  - username: roo_code_client
    plugins:
      key-auth:
        key: "VIGOLEONROCKS_ROO_CODE_API_KEY" # Usar variable de entorno en producción
        # Se pueden añadir más configuraciones, como rate limiting por consumidor

# ... aquí se pueden añadir más consumidores para otros clientes ...
